### PR TITLE
TRIVIAL: Missing includes

### PR DESCRIPTION
**Pull request by jtimon**
Unlike #5697, this should be trivial to rebase (and would make  #5697 easier to read if merged this way first).

### CODE REVIEW

**Comment by theuni** [comment]
I appreciate the idea here, but I don't think this really ends up making things any easier. There's no easy way for me to review which of these are needed for some future changes.

IMO for big refactors, it makes sense to just tack these changes onto the PR that necessitates them.

**Comment by jtimon** [comment]
One possible way to "easily review" this could be to take only the second commit in #5697 and then try to compile, adding necessary includes as required. 
By just commenting #include "main.h" everywhere and trying to compile you get most of them. 

I can always close this and just maintain #5697 (although I'm not sure I will get more review time there).

**Comment by theuni** [comment]
This (or something like it) went into master. Closing.

**Comment by jtimon** [comment]
Yeah, sorry, I thought I had closed this.

**Pull request closed without merging**
