### PR TITLE
Made the ForEachNode* functions in src/net.cpp more pragmatic and self documenting

### PR DESCRIPTION
**Pull request by JeremyRubin**

### CODE REVIEW

**Comment by theuni** [comment]
Thanks!

(On mobile, so bear with me)

On the encapsulation PR, kaz suggested dropping the std::function arg in
favor of a templated Callable in the header, to avoid incurring the stl
overhead for simple lambdas.

I think that's a good idea. Mind doing that at the same time here?

So It'd look something like (all in the header)

template <typename Callable>
void ForEachNode(Callable&& func)
{
LOCK..
for(nodes...){
  func(node);
}
}

Also, if it would end up being simpler, you could implement them all terms
of a basic (private, possibly static) version with no locking.

With that, I believe it's also possible to eliminate ForEachNodeThen in
favor of passing in a callable object, with its "then" function simply
defined as its destructor. I'm not looking at the code now though, so i
could be wrong on that.

**Comment by JeremyRubin** [comment]
Sure will code it up later today.

I don't think I'll do the destructor version as that seems fragile.

**Comment by theuni** [comment]
(I replied with this before, but seems it didn't go through. Disregard if this is a dupe)

Thanks! Looks good.

Nits:
- leading whitespace on some of the template lines
- are those tabs I see? 4 spaces please.

**Comment by JeremyRubin** [comment]
Should be all set.

**Comment by theuni** [comment]
Thanks, cherry-picked in.

**Pull request closed without merging**
